### ISSUE TITLE
Transparent background is not preserved

### ISSUE THREAD

**Issue by ttencate** [eowise/gradle-packer-plugin#10]
Thanks for making this plugin! It's a life-saver. Much better than the custom Makefile I keep dragging from project to project because I can't be bothered to learn Gradle ;)

But there's one issue: transparency in SVG files is not being preserved. When I have an SVG that doesn't cover all of its canvas, the remainder is being filled up with white, rather than transparent.

If [this post](http://stackoverflow.com/a/18579465/14637) is to be believed, it might be as simple as adding `-background none` somewhere around [here](https://github.com/eowise/gradle-packer-plugin/blob/master/src/main/groovy/com/eowise/packer/Packer.groovy#L129).

**Comment by acatinon** [comment]
Thanks for pointing this out!

I will push a fix tonight.

**Comment by acatinon** [comment]
Done!

**Comment by ttencate** [comment]
Wow, that was quick! Works like a charm! Merci beaucoup!
