### ISSUE TITLE
Upload 0.7.0 to central

### ISSUE THREAD

**Issue by palador** [eowise/gradle-packer-plugin#9]
Hi eowise, please upload the latest version to central. The given example setup won't work otherwise.

Thx

**Comment by acatinon** [comment]
Ooops it is an oversight, I will release the 0.7.0 version tonight.

You can use the 0.6.1 version in the meantime

**Comment by acatinon** [comment]
Done!

**Comment by acatinon** [comment]
BTW, notice that version 0.7.0 is on jCenter, not mavenCentral.

**Comment by palador** [comment]
OK thx!
